### ISSUE TITLE
How to display ListView in Reverse Order (Latest First on Top)?

### ISSUE THREAD

**Issue by iamlalitahuja** [mitchtabian/SaveReadWriteDeleteSQLite#1]
I want to display the newly added data on top in ListView. But it's getting added to the bottom. 
I tried changing INCREMENT to DESC and even posted the ques on StackOverflow but couldn't find any solution. Please Help.

**Comment by mitchtabian** [comment]
You shouldn't use this repo anymore. It's outdated and the best practice
way is to use room.

Here is a free course I made
https://codingwithmitch.com/courses/sqlite-room-persistence-android/

And if you want to change the order that the query objects are retrieved in
you just add ASC or DESC to the SQL statement.
